AWSTemplateFormatVersion: 2010-09-09
Description: Lilly GISS China Pilot Application S3 Buckets ---Robin
# liily Public Bucket creation
Resources:
  llycngispilotrobinpublic:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      BucketName: lly-cn-gis-robin-pilot-public
      PublicAccessBlockConfiguration:
        BlockPublicAcls: 'TRUE'
        BlockPublicPolicy: 'TRUE'
        IgnorePublicAcls: 'TRUE'
        RestrictPublicBuckets: 'TRUE'
      CorsConfiguration:
        CorsRules:
          - 
            AllowedHeaders:
                - '*'
            AllowedMethods:
                - PUT
                - GET
            AllowedOrigins:
                - 'http://localhost:4202'
                - 'http://localhost:4201'
                - 'http://localhost:4200'

            ExposedHeaders:
                - ETag
    # Bucket Lifecyle COnfiguratoin
      LifecycleConfiguration:
        Rules:
        - Id: Retention Policy
          Status: Enabled
          NoncurrentVersionExpirationInDays: 35
      VersioningConfiguration: 
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      Tags:
        - Key: "SystemCustodian"
          Value: "129121"
        - Key: "SystemOwner"
          Value: "2169288"
        - Key: "PrimaryItContact"
          Value: "2155037"
        - Key: "CostCenter"
          Value: "5205061"
        - Key: "CostCenterApprover"
          Value: "2032820"
        - Key: "ProjectName"
          Value: "CFC"
        - Key: "Level1BusinessArea"
          Value: "IBU"
  # Bucket Policy for Cloud Front and Deny Non Https access
  llycngispilotrobinpublicpolicy:
    Type: "AWS::S3::BucketPolicy"
    DependsOn:
    - llycngispilotrobinpublic
    Properties:
      Bucket:
        !Ref: llycngispilotrobinpublic
      PolicyDocument:
        Statement:
        - 
            Sid: Deny non-HTTPS access
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource: 'arn:aws-cn:s3:::lly-cn-gis-robin-pilot-public/*'
            Condition:
                Bool:
                    'aws:SecureTransport': 'false'
        - 
            Sid: Cloudfront config
            Effect: Allow
            Principal:
                AWS: 'arn:aws-cn:iam::cloudfront:user/CloudFront Origin Access Identity E16A6I8GQC5WPH'  # Test Cloud Front ID
            Action: 's3:GetObject'
            Resource: 'arn:aws-cn:s3:::lly-cn-gis-robin-pilot-public/*'

 # liily Private Bucket creation
  llycngispilotrobinprivate:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      BucketName: lly-cn-gis-robin-pilot-private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: 'TRUE'
        BlockPublicPolicy: 'TRUE'
        IgnorePublicAcls: 'TRUE'
        RestrictPublicBuckets: 'TRUE'
      CorsConfiguration:
        CorsRules:
          - 
            AllowedHeaders:
                - '*'
            AllowedMethods:
                - PUT
                - GET
            AllowedOrigins:
                - 'http://localhost:4202'
                - 'http://localhost:4201'
                - 'http://localhost:4200'
            ExposedHeaders:
                - ETag
      LifecycleConfiguration:
        Rules:
        - Id: Retention Policy
          Status: Enabled
          NoncurrentVersionExpirationInDays: 35
      VersioningConfiguration: 
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
      Tags:
        - Key: "SystemCustodian"
          Value: "129121"
        - Key: "SystemOwner"
          Value: "2169288"
        - Key: "PrimaryItContact"
          Value: "2155037"
        - Key: "CostCenter"
          Value: "5205061"
        - Key: "CostCenterApprover"
          Value: "2032820"
        - Key: "ProjectName"
          Value: "CFC"
        - Key: "Level1BusinessArea"
          Value: "IBU"
  llycngispilotrobinprivatepolicy:
    Type: "AWS::S3::BucketPolicy"
    DependsOn:
    - llycngispilotrobinprivate
    Properties:
      Bucket:
        Ref: "llycngispilotrobinprivate"
      PolicyDocument:
        Statement:
        - 
            Sid: Deny non-HTTPS access
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource: 'arn:aws-cn:s3:::lly-cn-gis-robin-pilot-private/*'
            Condition:
                Bool:
                    'aws:SecureTransport': 'false'
#Lilly IAM Users Group for Public Bucket access
  llycngispilotrobinpubliciam:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "IAM Policy for IAM Group for S3 Application"
      ManagedPolicyName: "lly-cn-gis-robin-pilot-public"
      Path: "/"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - 
          Effect: Allow
          Action:
              - 'kms:Describe*'
          Resource:
              - '*'
        - 
          Effect: Allow
          Action:
              - 's3:PutObject'
              - 's3:GetObject'
              - 's3:ListBucket'
              - 's3:DeleteObject'
              - 's3:DeleteObjectVersion'
              - 's3:GetObjectAcl'
              - 's3:GetObjectVersion'
              - 's3:GetObjectVersionAcl'
              - 's3:PutObjectTagging'
              - 's3:PutObjectVersionTagging'
              - 's3:RestoreObject'
              - 's3:GetBucketLocation'
              - 's3:GetBucketVersioning'
              - 's3:ListBucketVersions'
              - 's3:GetMetricsConfiguration'
          Resource:
              - 'arn:aws-cn:s3:::lly-cn-gis-robin-pilot-public'
              - 'arn:aws-cn:s3:::lly-cn-gis-robin-pilot-public/*'
      Groups:
        - lly-cn-gis-robin-pilot-public
#Lilly IAM Users Group for Private Bucket access
  llycngispilotrobinprivateiam:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "IAM Policy for IAM Group for S3 Application"
      ManagedPolicyName: "lly-cn-gis-robin-pilot-private"
      Path: "/"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - 
          Effect: Allow
          Action:
              - 'kms:Describe*'
          Resource:
              - '*'
        - 
          Effect: Allow
          Action:
              - 's3:PutObject'
              - 's3:GetObject'
              - 's3:ListBucket'
              - 's3:DeleteObject'
              - 's3:DeleteObjectVersion'
              - 's3:GetObjectAcl'
              - 's3:GetObjectVersion'
              - 's3:GetObjectVersionAcl'
              - 's3:PutObjectTagging'
              - 's3:PutObjectVersionTagging'
              - 's3:RestoreObject'
              - 's3:GetBucketLocation'
              - 's3:GetBucketVersioning'
              - 's3:ListBucketVersions'
              - 's3:GetMetricsConfiguration'
          Resource:
              - 'arn:aws-cn:s3:::lly-cn-gis-robin-pilot-private'
              - 'arn:aws-cn:s3:::lly-cn-gis-robin-pilot-private/*'
      Groups:
        - lly-cn-gis-robin-pilot-private